services:
  - type: web
    name: queuelab-api
    runtime: docker
    dockerfilePath: Backend/Dockerfile
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: CORS_ORIGINS
        sync: false
